Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Http\\Controllers\\AdministrationController",
            "name": "AdministrationController",
            "summary": "",
            "url": "classes/App-Http-Controllers-AdministrationController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AdministrationController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Muestra\u0020el\u0020listado\u0020de\u0020stocks.",
            "url": "classes/App-Http-Controllers-AdministrationController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AdministrationController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "",
            "url": "classes/App-Http-Controllers-AdministrationController.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AdministrationController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Muestra\u0020el\u0020formulario\u0020para\u0020crear\u0020un\u0020nuevo\u0020stock.",
            "url": "classes/App-Http-Controllers-AdministrationController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AdministrationController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Guarda\u0020un\u0020nuevo\u0020stock\u0020en\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/App-Http-Controllers-AdministrationController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AdministrationController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Muestra\u0020un\u0020registro\u0020concreto\u0020de\u0020stock.",
            "url": "classes/App-Http-Controllers-AdministrationController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AdministrationController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Muestra\u0020el\u0020formulario\u0020para\u0020editar\u0020un\u0020stock\u0020existente.",
            "url": "classes/App-Http-Controllers-AdministrationController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AdministrationController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Actualiza\u0020un\u0020stock\u0020en\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/App-Http-Controllers-AdministrationController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AdministrationController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Elimina\u0020un\u0020registro\u0020de\u0020stock\u0020de\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/App-Http-Controllers-AdministrationController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ConfirmPasswordController",
            "name": "ConfirmPasswordController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-ConfirmPasswordController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ConfirmPasswordController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020controller\u0020instance.",
            "url": "classes/App-Http-Controllers-Auth-ConfirmPasswordController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ConfirmPasswordController\u003A\u003A\u0024redirectTo",
            "name": "redirectTo",
            "summary": "Where\u0020to\u0020redirect\u0020users\u0020when\u0020the\u0020intended\u0020url\u0020fails.",
            "url": "classes/App-Http-Controllers-Auth-ConfirmPasswordController.html#property_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ForgotPasswordController",
            "name": "ForgotPasswordController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-ForgotPasswordController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController",
            "name": "LoginController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020controller\u0020instance.",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController\u003A\u003AshowLoginForm\u0028\u0029",
            "name": "showLoginForm",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html#method_showLoginForm"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController\u003A\u003A\u0024redirectTo",
            "name": "redirectTo",
            "summary": "Where\u0020to\u0020redirect\u0020users\u0020after\u0020login.",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html#property_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController",
            "name": "RegisterController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020controller\u0020instance.",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003Avalidator\u0028\u0029",
            "name": "validator",
            "summary": "Get\u0020a\u0020validator\u0020for\u0020an\u0020incoming\u0020registration\u0020request.",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#method_validator"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020new\u0020user\u0020instance\u0020after\u0020a\u0020valid\u0020registration.",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003A\u0024redirectTo",
            "name": "redirectTo",
            "summary": "Where\u0020to\u0020redirect\u0020users\u0020after\u0020registration.",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#property_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ResetPasswordController",
            "name": "ResetPasswordController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-ResetPasswordController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ResetPasswordController\u003A\u003A\u0024redirectTo",
            "name": "redirectTo",
            "summary": "Where\u0020to\u0020redirect\u0020users\u0020after\u0020resetting\u0020their\u0020password.",
            "url": "classes/App-Http-Controllers-Auth-ResetPasswordController.html#property_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\VerificationController",
            "name": "VerificationController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-VerificationController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\VerificationController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020controller\u0020instance.",
            "url": "classes/App-Http-Controllers-Auth-VerificationController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\VerificationController\u003A\u003A\u0024redirectTo",
            "name": "redirectTo",
            "summary": "Where\u0020to\u0020redirect\u0020users\u0020after\u0020verification.",
            "url": "classes/App-Http-Controllers-Auth-VerificationController.html#property_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\BrandController",
            "name": "BrandController",
            "summary": "",
            "url": "classes/App-Http-Controllers-BrandController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\BrandController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-BrandController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\BrandController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Http-Controllers-BrandController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\BrandController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-BrandController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\BrandController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "",
            "url": "classes/App-Http-Controllers-BrandController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\BrandController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/App-Http-Controllers-BrandController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\BrandController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Http-Controllers-BrandController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\BrandController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/App-Http-Controllers-BrandController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CartController",
            "name": "CartController",
            "summary": "",
            "url": "classes/App-Http-Controllers-CartController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CartController\u003A\u003AisUserAuthenticated\u0028\u0029",
            "name": "isUserAuthenticated",
            "summary": "Verifica\u0020si\u0020el\u0020usuario\u0020est\u00E1\u0020autenticado.",
            "url": "classes/App-Http-Controllers-CartController.html#method_isUserAuthenticated"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CartController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Muestra\u0020la\u0020vista\u0020del\u0020carrito\u0020con\u0020los\u0020productos\u0020agregados.",
            "url": "classes/App-Http-Controllers-CartController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CartController\u003A\u003AgetCartItemCount\u0028\u0029",
            "name": "getCartItemCount",
            "summary": "Obtiene\u0020la\u0020cantidad\u0020total\u0020de\u0020productos\u0020en\u0020el\u0020carrito.",
            "url": "classes/App-Http-Controllers-CartController.html#method_getCartItemCount"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CartController\u003A\u003AaddToCart\u0028\u0029",
            "name": "addToCart",
            "summary": "Agrega\u0020un\u0020zapato\u0020al\u0020carrito.",
            "url": "classes/App-Http-Controllers-CartController.html#method_addToCart"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CartController\u003A\u003AremoveFromCart\u0028\u0029",
            "name": "removeFromCart",
            "summary": "Elimina\u0020un\u0020zapato\u0020del\u0020carrito.",
            "url": "classes/App-Http-Controllers-CartController.html#method_removeFromCart"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CartController\u003A\u003AclearCart\u0028\u0029",
            "name": "clearCart",
            "summary": "Vac\u00EDa\u0020completamente\u0020el\u0020carrito\u0020del\u0020usuario.",
            "url": "classes/App-Http-Controllers-CartController.html#method_clearCart"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CartController\u003A\u003AupdateQuantity\u0028\u0029",
            "name": "updateQuantity",
            "summary": "Actualiza\u0020la\u0020cantidad\u0020de\u0020un\u0020zapato\u0020en\u0020el\u0020carrito\u0020\u0028aumentar\u0020o\u0020disminuir\u0029.",
            "url": "classes/App-Http-Controllers-CartController.html#method_updateQuantity"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CartController\u003A\u003AimportLocalCart\u0028\u0029",
            "name": "importLocalCart",
            "summary": "Importa\u0020los\u0020productos\u0020del\u0020carrito\u0020local\u0020\u0028en\u0020sesi\u00F3n\u0029\u0020al\u0020carrito\u0020del\u0020usuario\u0020autenticado\u0020en\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/App-Http-Controllers-CartController.html#method_importLocalCart"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoryController",
            "name": "CategoryController",
            "summary": "",
            "url": "classes/App-Http-Controllers-CategoryController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoryController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020the\u0020resource.",
            "url": "classes/App-Http-Controllers-CategoryController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoryController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-CategoryController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoryController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage\u0020sisi.",
            "url": "classes/App-Http-Controllers-CategoryController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoryController\u003A\u003AtoggleStatus\u0028\u0029",
            "name": "toggleStatus",
            "summary": "",
            "url": "classes/App-Http-Controllers-CategoryController.html#method_toggleStatus"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoryController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-CategoryController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoryController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-CategoryController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoryController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-CategoryController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoryController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-CategoryController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ChartController",
            "name": "ChartController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ChartController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ChartController\u003A\u003AgetChartData\u0028\u0029",
            "name": "getChartData",
            "summary": "",
            "url": "classes/App-Http-Controllers-ChartController.html#method_getChartData"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ColorController",
            "name": "ColorController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ColorController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ColorController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-ColorController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ColorController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Http-Controllers-ColorController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ColorController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-ColorController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ColorController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/App-Http-Controllers-ColorController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ColorController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Http-Controllers-ColorController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ColorController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/App-Http-Controllers-ColorController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\GameController",
            "name": "GameController",
            "summary": "",
            "url": "classes/App-Http-Controllers-GameController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\GameController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-GameController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\GameController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-GameController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\HomeController",
            "name": "HomeController",
            "summary": "",
            "url": "classes/App-Http-Controllers-HomeController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\HomeController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020controller\u0020instance.",
            "url": "classes/App-Http-Controllers-HomeController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\HomeController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Show\u0020the\u0020application\u0020dashboard.",
            "url": "classes/App-Http-Controllers-HomeController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\HomeController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "",
            "url": "classes/App-Http-Controllers-HomeController.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\InvoiceController",
            "name": "InvoiceController",
            "summary": "",
            "url": "classes/App-Http-Controllers-InvoiceController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\InvoiceController\u003A\u003AgenerateInvoice\u0028\u0029",
            "name": "generateInvoice",
            "summary": "",
            "url": "classes/App-Http-Controllers-InvoiceController.html#method_generateInvoice"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\MerchandisingController",
            "name": "MerchandisingController",
            "summary": "",
            "url": "classes/App-Http-Controllers-MerchandisingController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\MerchandisingController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-MerchandisingController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\MerchandisingController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-MerchandisingController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrderController",
            "name": "OrderController",
            "summary": "",
            "url": "classes/App-Http-Controllers-OrderController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrderController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020the\u0020resource.",
            "url": "classes/App-Http-Controllers-OrderController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrderController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-OrderController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrderController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-OrderController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrderController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-OrderController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrderController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-OrderController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrderController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-OrderController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrderController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-OrderController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrderController\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "",
            "url": "classes/App-Http-Controllers-OrderController.html#method_search"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeController",
            "name": "ShoeController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeController\u003A\u003Apreview\u0028\u0029",
            "name": "preview",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeController.html#method_preview"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeController\u003A\u003AstockChart\u0028\u0029",
            "name": "stockChart",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeController.html#method_stockChart"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeModelController",
            "name": "ShoeModelController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeModelController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeModelController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeModelController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeModelController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeModelController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeModelController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeModelController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeModelController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeModelController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeModelController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeModelController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeModelController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeModelController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ShoeModelController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/App-Http-Controllers-ShoeModelController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SizeController",
            "name": "SizeController",
            "summary": "",
            "url": "classes/App-Http-Controllers-SizeController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SizeController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-SizeController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SizeController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Http-Controllers-SizeController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SizeController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-SizeController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SizeController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/App-Http-Controllers-SizeController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SizeController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Http-Controllers-SizeController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SizeController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/App-Http-Controllers-SizeController.html#method_destroy"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth",
            "name": "Auth",
            "summary": "",
            "url": "namespaces/app-http-controllers-auth.html"
        }            ]
);
